import { describe, expect, it } from "vitest";
import { decodeCapture, readInputLine } from "../src/hosts/input-line.ts";

/**
 * v0.11.38 — Claude Code's prompt suggestion is not a person's unsent text.
 *
 * WHAT HAPPENED. `peer_compact` on peer `ai-bridge-dev` failed in its send
 * stage on 2026-08-28: the clear-verify said the input line still held 47
 * characters after its clear strokes and refused to type onto them. Nobody had
 * written those characters. They were the client's own greyed-out suggestion
 * ("Zvedni ten stable flip mostu — jak na tom jsme?"), which `C-u` cannot clear
 * because the box is empty. The safeguard against typing on a human's sentence
 * fired against a sentence generated by the machine it was typing into.
 *
 * EVERY FIXTURE BELOW IS A MEASURED SHAPE, captured from live panes of this
 * fleet on 2026-08-28 with `tmux capture-pane -e -p`, or from a pane driven by
 * hand to produce the wrapped case. None is invented.
 */

const ESC = "\x1b";
/** The marker as Claude Code draws it: U+276F then U+00A0. */
const BOX = `${ESC}[39m❯  `;
const RULE = "─".repeat(60);

describe("prompt suggestion (dim) is not a draft", () => {
  it("one dim run — the sentence that broke peer_compact", () => {
    const pane = [
      `${BOX}${ESC}[2mZvedni ten stable flip mostu — jak na tom jsme?${ESC}[0m`,
      RULE,
    ].join("\n");
    const decoded = decodeCapture(pane);
    expect(readInputLine(decoded.plain)).toMatchObject({ kind: "draft" });
    expect(readInputLine(decoded.withoutGhosts)).toEqual({ kind: "empty" });
    // Non-blank characters only — the spaces between the words are not
    // counted, so this number is deliberately smaller than the character
    // count the refusal reported. Two measures, kept apart on purpose.
    expect(decoded.ghostChars).toBe(38);
  });

  it("one dim run PER WORD, with undimmed spaces between them", () => {
    // Measured on a live peer: the client emits every word as its own run.
    // Removing the runs leaves the spaces behind, so emptiness has to survive
    // a box that is blank rather than short.
    const words = ["jsi", "po", "compactu,", "detailní", "re-onboard"];
    const pane = [BOX + words.map((w) => `${ESC}[2m${w}${ESC}[0m`).join(" "), RULE].join("\n");
    expect(readInputLine(decodeCapture(pane).withoutGhosts)).toEqual({ kind: "empty" });
  });

  it("a WRAPPED suggestion: the run is declared once and carries across rows", () => {
    // THE CASE A PER-LINE FILTER CANNOT SEE. Measured by driving a pane by
    // hand: tmux emits `ESC[2m` on the first row of a wrapped dim run and
    // NOTHING on the continuation rows, which close the run at the end. A
    // regular expression applied line by line finds no terminated run on row
    // one and filters nothing at all.
    const pane = [
      `${BOX}${ESC}[2mZvedni ten stable flip mostu a rovnou taky`,
      `ostatní věci, které čekají na rozhodnutí${ESC}[0m`,
      RULE,
    ].join("\n");
    const decoded = decodeCapture(pane);
    expect(readInputLine(decoded.plain)).toMatchObject({ kind: "draft" });
    expect(readInputLine(decoded.withoutGhosts)).toEqual({ kind: "empty" });
  });

  it("a capture region declares its own starting state", () => {
    // Measured: capturing ONLY the continuation row of a wrapped run re-emits
    // `ESC[2m` at its head. So nothing is inherited from above the region and
    // the state machine is complete with what it is given.
    const continuationOnly = `${BOX}${ESC}[2mpokračování ztlumeného úseku${ESC}[0m`;
    expect(readInputLine(decodeCapture(continuationOnly).withoutGhosts)).toEqual({
      kind: "empty",
    });
  });
});

describe("a person's text is still a person's text", () => {
  it("undimmed text in the box stays a draft — the safeguard is not weakened", () => {
    const pane = [`${BOX}tohle napsal člověk a neodeslal to`, RULE].join("\n");
    const decoded = decodeCapture(pane);
    expect(decoded.ghostChars).toBe(0);
    expect(readInputLine(decoded.withoutGhosts)).toEqual({
      kind: "draft",
      text: "tohle napsal člověk a neodeslal to",
    });
  });

  it("dim ABOVE the box does not blank the draft inside it", () => {
    // `ESC[22m` and `ESC[0m` both end a run. A decoder that only honoured `0`
    // would carry dim down the pane and blank a real draft — the failure this
    // change must not introduce while removing the opposite one.
    const pane = [
      `${ESC}[2mnějaký ztlumený řádek nad boxem${ESC}[22m`,
      `${BOX}rozepsaná věta`,
      RULE,
    ].join("\n");
    expect(readInputLine(decodeCapture(pane).withoutGhosts)).toEqual({
      kind: "draft",
      text: "rozepsaná věta",
    });
  });

  it("blanking keeps the geometry a wrapped draft is un-wrapped by", () => {
    // Dimmed characters are replaced by spaces rather than deleted: the box is
    // un-wrapped by column arithmetic, and deleting would slide the rest of a
    // row left. Same length in, same length out.
    const decoded = decodeCapture(`x${ESC}[2mABCD${ESC}[0my`);
    expect(decoded.plain).toBe("xABCDy");
    expect(decoded.withoutGhosts).toBe("x    y");
  });
});

describe("plain view stays what the old predicates read", () => {
  it("strips OSC hyperlinks, SGR, and each row's trailing whitespace", () => {
    // Measured equality: OSC + SGR removed and rows right-trimmed reproduces
    // `capture-pane -p` byte for byte (checked on a static pane and on a live
    // pane that did not change between the two reads). That is why turning
    // `-e` on did not disturb the delivery predicates.
    const raw = [
      `${ESC}]8;id=1;file:///opt/claude-bridge${ESC}\\/opt/claude-bridge${ESC}]8;;${ESC}\\   `,
      `${ESC}[38;5;246mstavový řádek${ESC}[39m  `,
    ].join("\n");
    expect(decodeCapture(raw).plain).toBe("/opt/claude-bridge\nstavový řádek");
  });
});
